version: "3.8"
services:
  api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: LibreChat-API
    ports:
      - 8000:3080
    depends_on:
      - mongodb
    restart: always
    volumes:
      - ~/ai/data/librechat/images:/app/client/public/images
      - ~/ai/data/librechat/logs:/app/api/logs
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat

  mongodb:
    container_name: librechat-mongodb
    image: mongo
    restart: always
    volumes:
      - ~/ai/data/librechat/mongodb:/data/db
