version: '3.4'

services:
  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: always
    ports:
      - "4000:3000"
    volumes:
      - ~/ai/data/newapi:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=newapi:newapi123@tcp(vpsai-mysql:3306)/newapi
      - REDIS_CONN_STRING=redis://redis
      - TZ=Asia/Shanghai
    depends_on:
      - redis
      - mysql
    networks:
      - vpsai-net

  redis:
    image: redis:latest
    container_name: new-api-redis
    restart: always
    networks:
      - vpsai-net

  mysql:
    image: mysql:8.2
    container_name: new-api-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: new-api
    volumes:
      - ~/ai/data/newapi-mysql:/var/lib/mysql

networks:
  vpsai-net:
    external: true
