version: "3.9"
services:
  chatgpt-next-web:
    container_name: nextchat
    image: yidadaa/chatgpt-next-web
    ports:
      - 7000:3000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CODE=${CODE}
      - BASE_URL=${BASE_URL}
    volumes:
      - ~/ai/data/nextchat:/data
    restart: always
    networks:
      - vpsai-net

networks:
  vpsai-net:
    external: true