version: '3.8'

services:
  ollama:
    volumes:
      - ~/ai/data/open-webui/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    restart: unless-stopped
    image: ollama/ollama:latest

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ~/ai/data/open-webui/data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "6000:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    restart: unless-stopped
